#!/bin/sh

# Based on:
# https://github.com/firecracker-microvm/firecracker/blob/master/docs/rootfs-and-kernel-setup.md

### Common
apk add openrc
apk add util-linux

# Set up a login terminal on the serial console (ttyS0):
ln -s agetty /etc/init.d/agetty.ttyS0
echo ttyS0 > /etc/securetty
rc-update add agetty.ttyS0 default

# Make sure special file systems are mounted on boot:
#rc-update add devfs boot
#rc-update add procfs boot
#rc-update add sysfs boot

###

### Customize me!
# Build stuff
apk add gcc make musl-dev linux-headers

# Tools
apk add socat git
###

### Optional: Working dir
# mkdir -p /work

### Post install stuff
# Set up a login terminal on the serial console (ttyS0):
ln -s agetty /etc/init.d/agetty.ttyS0
echo ttyS0 > /etc/securetty
rc-update add agetty.ttyS0 default

# Set default password
echo "root:root" | chpasswd

# Enable autologin
echo "agetty_options=\"--autologin root\"" > /etc/conf.d/agetty-autologin

### Make sure special file systems are mounted on boot:
rc-update add devfs boot
rc-update add procfs boot
rc-update add sysfs boot

# Enable local.d scripts
rc-update add local default

# Optional: copy startup script
# cp /alpine_boot /etc/local.d/RunMe.start

# Then, copy the newly configured system to the rootfs image:
for d in bin etc lib root sbin usr work; do tar c "/$d" | tar x -C /my-rootfs; done
for dir in dev proc run sys var; do mkdir /my-rootfs/${dir}; done

# All done, exit docker shell
exit
